variables:
  CustomVersion: "2.9.0"

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: none

  - powershell: |
      $version = "$(CustomVersion)"
      New-Item "version.txt"
      Set-Content version.txt $version
      Get-Content version.txt
    displayName: 'create version file as build artifact'

  - task: CopyFiles@2
    inputs:
        contents: 'version.txt'
        targetFolder: $(Build.ArtifactStagingDirectory)/ReleaseVersionFile
    displayName: 'copy version file to Build.ArtifactStagingDirectory'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/ReleaseVersionFile/version.txt'
      ArtifactName: 'ReleaseVersionFile'
      publishLocation: 'Container'
