# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none
pr: none

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  CurrentBranch: $(Build.SourceBranchName)
  ProjectId: '__PROJECT_ID__'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: SiteData
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/surveyjs-site-data
    - repository: Library # The name used to reference this repository in the checkout step
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-library
    - repository: Creator
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-creator
    - repository: Analytics
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-analytics
    - repository: PDF
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-pdf
  pipelines:
    - pipeline: RunRelease
      source: Run Release
      trigger: true


steps:
- task: NodeTool@0
  inputs:
    versionSpec: "24.x"
  displayName: "Install Node.js"

- checkout: SiteData
  persistCredentials: true
  clean: true
  fetchDepth: 1
- checkout: Library
  persistCredentials: true
  clean: true
  fetchDepth: 1
- checkout: Creator
  persistCredentials: true
  clean: true
  fetchDepth: 1
- checkout: Analytics
  persistCredentials: true
  clean: true
  fetchDepth: 1
- checkout: PDF
  persistCredentials: true
  clean: true
  fetchDepth: 1

- task: CopyFiles@2
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/surveyjs-site-data/DocsLibrary"
    Contents: |
      **
      !classes.json
      !pmes.json
#      !surveyjs_definition.json
    TargetFolder: "$(Build.SourcesDirectory)/survey-library/docs"
    CleanTargetFolder: true
    OverWrite: true
  displayName: "Library - copy docs from service to github locally"

- task: CopyFiles@2
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/surveyjs-site-data/DocsEditor"
    Contents: |
      **
      !classes.json
      !pmes.json
#      !surveyjs_definition.json
    TargetFolder: "$(Build.SourcesDirectory)/survey-creator/docs"
    CleanTargetFolder: true
    OverWrite: true
  displayName: "Creator - copy docs from service to github locally"

- task: CopyFiles@2
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/surveyjs-site-data/DocsAnalytics"
    Contents: |
      **
      !classes.json
      !pmes.json
#      !surveyjs_definition.json
    TargetFolder: "$(Build.SourcesDirectory)/survey-analytics/docs"
    OverWrite: true
    CleanTargetFolder: true
  displayName: "Analytics - copy docs from service to github locally"

- task: CopyFiles@2
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/surveyjs-site-data/DocsPdf"
    Contents: |
      **
      !classes.json
      !pmes.json
#      !surveyjs_definition.json
    TargetFolder: "$(Build.SourcesDirectory)/survey-pdf/docs"
    CleanTargetFolder: true
    OverWrite: true
  displayName: "DocsPdf - copy docs from service to github locally"


# read about the problem with git output ($env:GIT_REDIRECT_STDERR = '2>&1') :
# https://github.com/microsoft/azure-pipelines-yaml/issues/248
# https://stackoverflow.com/questions/58485585/azure-pipeline-powershell-and-git-on-windows-server-2019-gives-error-in-output
- powershell: |
    cd $(Build.SourcesDirectory)/survey-library
    $env:GIT_REDIRECT_STDERR = '2>&1'
    git config --global user.email "surveyjs.org@gmail.com"
    git config --global user.name "surveyjsdeveloper"
    git pull origin $(CurrentBranch)
    git fetch origin $(CurrentBranch) --tags --force
    git checkout $(CurrentBranch)
    git add docs
    git commit -m "updated survey-library docs [azurepipelines skip]"
    git pull origin $(CurrentBranch)
    git push origin $(CurrentBranch)
  displayName: "Library - push docs to github"
  
- powershell: |
    cd $(Build.SourcesDirectory)/survey-creator
    $env:GIT_REDIRECT_STDERR = '2>&1'
    git config --global user.email "surveyjs.org@gmail.com"
    git config --global user.name "surveyjsdeveloper"
    git pull origin $(CurrentBranch)
    git fetch origin $(CurrentBranch) --tags --force
    git checkout $(CurrentBranch)
    git add docs
    git commit -m "updated survey-creator docs [azurepipelines skip]"
    git pull origin $(CurrentBranch)
    git push origin $(CurrentBranch)
  displayName: "Creator - push docs to github"

- powershell: |
    cd $(Build.SourcesDirectory)/survey-analytics
    $env:GIT_REDIRECT_STDERR = '2>&1'
    git config --global user.email "surveyjs.org@gmail.com"
    git config --global user.name "surveyjsdeveloper"
    git pull origin $(CurrentBranch)
    git fetch origin $(CurrentBranch) --tags --force
    git checkout $(CurrentBranch)
    git add docs
    git commit -m "updated survey-analytics docs [azurepipelines skip]"
    git pull origin $(CurrentBranch)
    git push origin $(CurrentBranch)
  displayName: "Analytics - push docs to github"

- powershell: |
    cd $(Build.SourcesDirectory)/survey-pdf
    $env:GIT_REDIRECT_STDERR = '2>&1'
    git config --global user.email "surveyjs.org@gmail.com"
    git config --global user.name "surveyjsdeveloper"
    git pull origin $(CurrentBranch)
    git fetch origin $(CurrentBranch) --tags --force
    git checkout $(CurrentBranch)
    git add docs
    git commit -m "updated survey-pdf docs [azurepipelines skip]"
    git pull origin $(CurrentBranch)
    git push origin $(CurrentBranch)
  displayName: "PDF - push docs to github"