trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

# #comment for custom version
resources:
  pipelines:
    - pipeline: RunRelease
      source: Run Release
      trigger: true
# #EO comment for custom version

steps:
  - checkout: none

# #comment for custom version
  - download: RunRelease
    artifact: ReleaseVersionFile

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)/RunRelease/ReleaseVersionFile'
      ArtifactName: 'ReleaseVersionFile'
      publishLocation: 'Container'
# #EO comment for custom version

# #uncomment for custom version (comment out download + Publish above)
#  - powershell: |
#      $version = "2.9.0"
#      New-Item "version.txt"
#      Set-Content version.txt $version
#      Get-Content version.txt
#    displayName: 'create version file as build artifact'
#
#  - task: CopyFiles@2
#    inputs:
#        contents: 'version.txt'
#        targetFolder: $(Build.ArtifactStagingDirectory)/ReleaseVersionFile
#    displayName: 'copy version file to Build.ArtifactStagingDirectory'
#
#  - task: PublishBuildArtifacts@1
#    inputs:
#      PathtoPublish: '$(Build.ArtifactStagingDirectory)/ReleaseVersionFile/version.txt'
#      ArtifactName: 'ReleaseVersionFile'
#      publishLocation: 'Container'
# #EO uncomment for custom version (comment out download + Publish above)
