#trigger only "by hand"
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: none

#uncomment for specific version
  - powershell: |
      $version = "2.5.0"
      New-Item "version.txt"
      Set-Content version.txt $version
      Get-Content version.txt
    displayName: 'create version file as build artifact'

  - task: CopyFiles@2
    inputs:
        contents: 'version.txt'
        targetFolder: $(Build.ArtifactStagingDirectory)/ReleaseVersionFile
    displayName: 'copy version file to Build.ArtifactStagingDirectory'
#######################################################################

#comment for specific version
  # - task: DownloadBuildArtifacts@0
  #   inputs:
  #     buildType: 'specific'
  #     project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
  #     pipeline: '45'
  #     buildVersionToDownload: 'latest'
  #     downloadType: 'single'
  #     artifactName: 'ReleaseVersionFile'
  #     downloadPath: '$(System.ArtifactsDirectory)'
#########################################################################

  #publishLocation: 'Container' - store the artifact in Azure Pipelines
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/ReleaseVersionFile/version.txt'
      ArtifactName: 'ReleaseVersionFile'
      publishLocation: 'Container'
