jobs:
  - job:
    steps:
      - checkout: self
        persistCredentials: true
        displayName: "Checkout survey-analytics"
        timeoutInMinutes: 5

      - checkout: Utils
        displayName: "Checkout survey-utils"
        timeoutInMinutes: 5

      - checkout: SiteData
        persistCredentials: true
        displayName: "Checkout survey-site-data"
        timeoutInMinutes: 5

      - template: ../utils/artifact.yml
        parameters:
          artifacts:
            - $(ArtifactNameLibraryCore)

      - pwsh: |
          $dest = "$(Build.SourcesDirectory)/survey-library/packages/survey-core/build"
          New-Item -ItemType Directory -Force -Path $dest | Out-Null
          Copy-Item -Recurse -Force "$(Agent.TempDirectory)/$(ArtifactNameLibraryCore)/*" $dest
        displayName: "Provide survey-core build"

      - script: |
          npm install --legacy-peer-deps
        workingDirectory: $(Build.SourcesDirectory)/survey-analytics
        displayName: "npm install"

      - pwsh: |
          Set-Location $(Build.SourcesDirectory)/survey-utils
          npm install
          npm run build
          node ./dist/translateAnalytics.js

          Set-Location $(Build.SourcesDirectory)/survey-analytics
          $branch = "$(Build.SourceBranchName)"
          $env:GIT_REDIRECT_STDERR = '2>&1'
          git config user.email "surveyjs.org@gmail.com"
          git config user.name "surveyjsdeveloper"

          git fetch origin $branch
          git checkout -B $branch origin/$branch

          git add src/analytics-localization
          if (git status --porcelain) {
              echo "There are changes in translations. Committing and pushing to GitHub..."
              git diff --cached --stat
              git commit -m "updated survey-analytics translation for $branch [azurepipelines skip]"
              git push origin $branch
          }
          else {
              echo "No changes in translations. Skipping commit and push."
          }
        displayName: "l10n for $(Build.SourceBranchName)"

      - script: |
          npm run release -- --skip.tag
          npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/survey-analytics
        displayName: "Build"

      - pwsh: |
          Set-Location $(Build.SourcesDirectory)/survey-analytics
          npm run doc:gen
          Copy-Item -Force "docs/surveyjs_definition.json" "build/surveyjs_definition.json"

          Set-Location $(Build.SourcesDirectory)/surveyjs-site-data
          $branch = "$(Build.SourceBranchName)"
          $env:GIT_REDIRECT_STDERR = '2>&1'
          git config user.email "surveyjs.org@gmail.com"
          git config user.name "surveyjsdeveloper"

          git fetch origin $branch
          git checkout -B $branch origin/$branch
          git reset --hard origin/$branch

          Copy-Item -Force "$(Build.SourcesDirectory)/survey-analytics/docs/classes.json" "DocsAnalytics/"
          Copy-Item -Force "$(Build.SourcesDirectory)/survey-analytics/docs/pmes.json" "DocsAnalytics/"
          Copy-Item -Force "$(Build.SourcesDirectory)/survey-analytics/docs/surveyjs_definition.json" "DocsAnalytics/"

          git add DocsAnalytics
          if (git status --porcelain) {
              echo "There are changes in docs. Committing and pushing to GitHub..."
              git diff --cached --stat
              git commit -m "updated survey-analytics docs for $branch [azurepipelines skip]"
              git push origin $branch
          }
          else {
              echo "No changes in docs. Skipping commit and push."
          }
        displayName: "Docs for $(Build.SourceBranchName)"
