parameters:
  - name: checkout
    type: string
    default: self

jobs:
  - job:
    displayName: "Unit"
    condition: eq(variables['SCR_UPDATE'], '')
    steps:
      - template: build.yml
        parameters:
          checkout: ${{ parameters.checkout }}

      - script: npm run test
        workingDirectory: $(Build.SourcesDirectory)
        displayName: "Test"

      # - task: PublishCodeCoverageResults@1
      #   inputs:
      #     codeCoverageTool: Cobertura # or JaCoCo
      #     summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      #     reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"

  - job:
    displayName: "E2E"
    condition: eq(variables['SCR_UPDATE'], '')
    steps:
      - template: build.yml
        parameters:
          checkout: ${{ parameters.checkout }}

      - script: npm run pwinst
        displayName: "Playwright install"      
        
      - script: npm run e2e:ci
        displayName: "Test"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/test-results"
          ArtifactName: "Analytics_E2E"
          publishLocation: "Container"
        condition: always()
        displayName: "Publish artifacts"

      - task: PublishTestResults@2
        displayName: "Publish e2e test results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "Publish E2E test results"
        condition: succeededOrFailed()

  - job:
    displayName: "SCR Update"
    condition: and(ne(variables['SCR_UPDATE'], ''), ne(variables['System.PullRequest.SourceBranch'], ''))
    steps:
      - template: build.yml
        parameters:
          checkout: ${{ parameters.checkout }}

      - script: npm run pwinst
        displayName: "Playwright install"

      - script: npx playwright test --project chromium --update-snapshots
        workingDirectory: $(Build.SourcesDirectory)
        displayName: "Update SCR"

      - powershell: |
          $env:GIT_REDIRECT_STDERR = '2>&1'
          git config --global user.email "surveyjs.org@gmail.com"
          git config --global user.name "surveyjsdeveloper"
          git add $(Build.SourcesDirectory)/e2e
          $total = (git diff --cached --name-only | Measure-Object -Line).Lines
          git commit --allow-empty -m "updated $total screenshots" --no-verify
          git fetch origin "$(System.PullRequest.SourceBranch)"
          git rebase --onto "origin/$(System.PullRequest.SourceBranch)" HEAD~1
          git push --no-verify origin "HEAD:$(System.PullRequest.SourceBranch)"
        displayName: "commit updated screenshots"

