# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  - template: templates/utils/variables.yml

resources:
  repositories:
    - repository: Library
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-library
      ref: $(System.PullRequest.TargetBranch)
    - repository: Creator
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-creator
      ref: $(System.PullRequest.TargetBranch)
    - repository: Analytics
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-analytics
      ref: $(System.PullRequest.TargetBranch)
    - repository: PDF
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-pdf
      ref: $(System.PullRequest.TargetBranch)

stages:
  - stage: Lint
    dependsOn: []
    jobs:
      - job:
        steps:
          - checkout: self
            timeoutInMinutes: 5
            retryCountOnTaskFailure: 5
            fetchDepth: 1
          
          - template: templates/utils/npm.yml
            parameters:
              directories:
                - $(Build.SourcesDirectory)

          - script: npm run lint
            workingDirectory: $(Build.SourcesDirectory)

  - stage: Options
    dependsOn: []
    jobs:
      - job: PRTitle
        displayName: "Parse PR title"
        steps:
          - template: templates/utils/pr_title_parser.yml

  - stage: LibraryCoreBuild
    displayName: "Library Core Build"
    dependsOn:
      - Options
    variables:
      PR: $[ stageDependencies.Options.PRTitle.outputs['data.LIBRARY'] ]
    jobs:
      - job:
        steps:
          - template: templates/library/core/build.yml
            parameters:
              checkout: Library
              store: true

  - stage: Analytics
    displayName: "Analytics"
    dependsOn:
      - LibraryCoreBuild
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/analytics/build.yml
            parameters:
              store: true
      - template: templates/analytics/test.yml
