# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  - template: templates/utils/variables.yml

resources:
  repositories:
    - repository: Library
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-library
      ref: $(System.PullRequest.TargetBranch)
    - repository: Creator
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-creator
      ref: $(System.PullRequest.TargetBranch)
    - repository: Analytics
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-analytics
      ref: $(System.PullRequest.TargetBranch)
    - repository: PDF
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/survey-pdf
      ref: $(System.PullRequest.TargetBranch)

stages:
  - stage: Lint
    dependsOn: []
    jobs:
      - job:
        steps:
          - checkout: self
          
          - template: templates/utils/npm.yml
            parameters:
              directories:
                - $(Build.SourcesDirectory)

          - script: npm run lint
            workingDirectory: $(Build.SourcesDirectory)

  - stage: Options
    dependsOn: []
    jobs:
      - job: PRTitle
        displayName: "Parse PR title"
        steps:
          - template: templates/utils/pr_title_parser.yml
      - job: Commit
        displayName: "Commit message"
        steps:
          - template: templates/utils/commit_message_parser.yml

  ###########
  # LIBRARY #
  ###########
  - stage: LibraryCoreBuild
    displayName: "Library Core Build"
    dependsOn:
      - Options
    variables:
      PR: $[ stageDependencies.Options.PRTitle.outputs['data.LIBRARY'] ]
    jobs:
      - job:
        steps:
          - template: templates/library/core/build.yml
            parameters:
              store: true

  - stage: LibraryReactBuild
    displayName: "Library React Build"
    dependsOn:
      - Options
    variables:
      PR: $[ stageDependencies.Options.PRTitle.outputs['data.LIBRARY'] ]
    jobs:
      - job:
        steps:
          - template: templates/library/react/build.yml
            parameters:
                store: true

  - stage: LibraryAngularBuild
    displayName: "Library Angular Build"
    dependsOn:
      - Options
    variables:
      PR: $[ stageDependencies.Options.PRTitle.outputs['data.LIBRARY'] ]
    jobs:
      - job:
        steps:
          - template: templates/library/angular/build.yml
            parameters:
                store: true

  - stage: LibraryVueBuild
    displayName: "Library Vue Build"
    dependsOn:
      - Options
    variables:
      PR: $[ stageDependencies.Options.PRTitle.outputs['data.LIBRARY'] ]
    jobs:
      - job:
        steps:
          - template: templates/library/vue/build.yml
            parameters:
                store: true

  - stage: LibraryJSBuild
    displayName: "Library JS (Preact ShadowDOM BoxSizing) Build"
    dependsOn:
      - Options
    variables:
      PR: $[ stageDependencies.Options.PRTitle.outputs['data.LIBRARY'] ]
    jobs:
      - job:
        steps:
          - template: templates/library/js/build.yml
            parameters:
                store: true


  ###########
  # CREATOR #
  ###########
  - stage: CreatorCore
    displayName: "Creator Core"
    dependsOn:
      - Options
      - LibraryCoreBuild
    condition: eq(dependencies.Options.outputs['Commit.data.SCR_UPDATE'], '')
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/core/build.yml
            parameters:
              store: true
      - template: templates/creator/core/test.yml

  - stage: CreatorReactBuild
    displayName: "Creator React"
    dependsOn:
      - Options
      - LibraryCoreBuild
      - LibraryReactBuild
    variables:
      SCR_UPDATE: $[ stageDependencies.Options.Commit.outputs['data.SCR_UPDATE'] ]
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/react/build.yml
            parameters:
              store: true
      - template: templates/creator/react/test.yml

  - stage: CreatorAngularBuild
    displayName: "Creator Angular"
    dependsOn:
      - Options
      - LibraryCoreBuild
      - LibraryAngularBuild
    condition: eq(dependencies.Options.outputs['Commit.data.SCR_UPDATE'], '')
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/angular/build.yml
            parameters:
              store: true
      - template: templates/creator/angular/test.yml

  - stage: CreatorVueBuild
    displayName: "Creator Vue"
    dependsOn:
      - Options
      - LibraryCoreBuild
      - LibraryVueBuild
    condition: eq(dependencies.Options.outputs['Commit.data.SCR_UPDATE'], '')
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/vue/build.yml
            parameters:
              store: true
      - template: templates/creator/vue/test.yml

  - stage: CreatorJSBuild
    displayName: "Creator JS (Preact ShadowDOM BoxSizing)"
    dependsOn:
      - Options
      - LibraryCoreBuild
      - LibraryJSBuild
    condition: eq(dependencies.Options.outputs['Commit.data.SCR_UPDATE'], '')
    jobs:
      - job:
        displayName: "Build"
        steps:
          - template: templates/creator/js/build.yml
            parameters:
              store: true
      - template: templates/creator/js/test.yml