parameters:
  - name: checkout
    type: string
    default: self
  - name: libraryCheckout
    type: string
    default: Library
  - name: store
    type: boolean
    default: false

steps:
  - checkout: ${{ parameters.checkout }}
    path: s
    timeoutInMinutes: 5
    retryCountOnTaskFailure: 5
    fetchDepth: 1
    persistCredentials: true
    displayName: "Checkout ${{ parameters.checkout }}"

  - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
    workingDirectory: $(Build.SourcesDirectory)
    condition: ne(variables['PR'], '')
    displayName: "Switch to PR $(PR)"

  - checkout: ${{ parameters.libraryCheckout }}
    path: s/survey-library
    persistCredentials: true
    timeoutInMinutes: 5
    retryCountOnTaskFailure: 5
    fetchDepth: 1
    displayName: "Checkout survey-library"

  - script: git fetch origin pull/$(LIBRARY_PR)/head && git checkout FETCH_HEAD
    workingDirectory: $(Build.SourcesDirectory)/survey-library
    condition: ne(variables['LIBRARY_PR'], '')
    displayName: "Switch library to PR $(LIBRARY_PR)"

  - template: ../../utils/npm.yml
    parameters:
      directories:
        - $(Build.SourcesDirectory)/survey-library
        - $(Build.SourcesDirectory)/survey-library/packages/survey-core
        - $(Build.SourcesDirectory)/survey-library/packages/survey-react-ui
        - $(Build.SourcesDirectory)
        - $(Build.SourcesDirectory)/packages/survey-creator-core
        - $(Build.SourcesDirectory)/packages/survey-creator-react
        - $(Build.SourcesDirectory)/packages/survey-creator-react/example

  - script: npm run build:all
    workingDirectory: $(Build.SourcesDirectory)/survey-library/packages/survey-core
    displayName: "Build survey-core"

  - script: npm run build
    workingDirectory: $(Build.SourcesDirectory)/survey-library/packages/survey-react-ui
    displayName: "Build survey-react-ui"

  - template: ../../utils/copy.yml
    parameters:
      items:
        - source: $(Build.SourcesDirectory)/survey-library/packages/survey-core/build
          destination: $(Build.SourcesDirectory)/packages/survey-creator-core/node_modules/survey-core
        - source: $(Build.SourcesDirectory)/survey-library/packages/survey-core/build
          destination: $(Build.SourcesDirectory)/packages/survey-creator-react/node_modules/survey-core
        - source: $(Build.SourcesDirectory)/survey-library/packages/survey-react-ui/build
          destination: $(Build.SourcesDirectory)/packages/survey-creator-react/node_modules/survey-react-ui

  - script: npm run build:all
    workingDirectory: $(Build.SourcesDirectory)/packages/survey-creator-core
    displayName: "Build Core"

  - script: npm run build
    workingDirectory: $(Build.SourcesDirectory)/packages/survey-creator-react
    displayName: "Build"

  - ${{ if eq(parameters.store, true) }}:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/packages/survey-creator-react/build/'
        ArtifactName: $(ArtifactNameCreatorReact)
        publishLocation: 'Container'
        StoreAsTar: true
