parameters:
  - name: checkout
    type: string
    default: self

jobs:
  - job:
    displayName: "Markup"
    condition: eq(variables['SCR_UPDATE'], '')
    steps:
      - template: build.yml
        parameters:
          checkout: ${{ parameters.checkout }}

      - script: npm run test
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-react-ui
        displayName: "Test Markup"

  - job:
    displayName: "A11Y & E2E"
    condition: eq(variables['SCR_UPDATE'], '')
    steps:
      - template: build.yml
        parameters:
          checkout: ${{ parameters.checkout }}

      - script: npm run accessibility-tests:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-react-ui
        displayName: "Test A11Y"

      - script: npm run e2e:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-react-ui
        displayName: "Test E2E"

      - task: PublishBuildArtifacts@1
        displayName: "Publish E2E artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-react-ui/test-results"
          ArtifactName: "Library_React_E2E"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish E2E results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-react-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "React E2E Tests"
        condition: succeededOrFailed()

  - job:
    displayName: "SCR Test"
    condition: eq(variables['SCR_UPDATE'], '')
    steps:
      - template: build.yml
        parameters:
          checkout: ${{ parameters.checkout }}

      - script: npm run scr:ci
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-react-ui
        displayName: "Test SCR"

      - task: PublishBuildArtifacts@1
        displayName: "Publish SCR artifacts"
        inputs:
          PathtoPublish: "$(Build.SourcesDirectory)/packages/survey-react-ui/test-results"
          ArtifactName: "Library_React_SCR"
          publishLocation: "Container"
        condition: always()

      - task: PublishTestResults@2
        displayName: "Publish SCR results"
        inputs:
          searchFolder: "$(Build.SourcesDirectory)/packages/survey-react-ui/test-results"
          testResultsFormat: "JUnit"
          testResultsFiles: "e2e-junit-results.xml"
          mergeTestResults: true
          failTaskOnFailedTests: true
          testRunTitle: "React SCR Tests"
        condition: succeededOrFailed()

  - job:
    displayName: "SCR Update"
    condition: and(ne(variables['SCR_UPDATE'], ''), ne(variables['System.PullRequest.SourceBranch'], ''))
    steps:
      - template: build.yml
        parameters:
          checkout: ${{ parameters.checkout }}

      - script: npm run scr:update
        workingDirectory: $(Build.SourcesDirectory)/packages/survey-react-ui
        displayName: "Update SCR"

      - powershell: |
          $env:GIT_REDIRECT_STDERR = '2>&1'
          git config --global user.email "surveyjs.org@gmail.com"
          git config --global user.name "surveyjsdeveloper"
          git add $(Build.SourcesDirectory)/screenshots
          if (git status --porcelain) {
              git commit -m "updated screenshots" --no-verify
              git pull --rebase origin "$(System.PullRequest.SourceBranch)"
              git push --no-verify origin "HEAD:$(System.PullRequest.SourceBranch)"
          }
        displayName: "commit updated screenshots"
