steps:
  - checkout: self
    persistCredentials: true
    displayName: "Checkout survey-creator"
    timeoutInMinutes: 5

  - checkout: SiteData
    persistCredentials: true
    displayName: "Checkout survey-site-data"
    timeoutInMinutes: 5

  - checkout: Library
    displayName: "Checkout survey-library"
    timeoutInMinutes: 5

  - template: ../utils/npm.yml
    parameters:
      directories:
        - $(Build.SourcesDirectory)/survey-library
        - $(Build.SourcesDirectory)/survey-library/packages/survey-core
        - $(Build.SourcesDirectory)/survey-creator
        - $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core

  - script: npm run build:all
    workingDirectory: $(Build.SourcesDirectory)/survey-library/packages/survey-core
    displayName: "Build survey-core"

  - script: npm update survey-utils
    workingDirectory: $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    displayName: "Update survey-utils dependency"
    
  - pwsh: |
      Set-Location $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run build:translate

      Set-Location $(Build.SourcesDirectory)/survey-creator
      $branch = "$(Build.SourceBranchName)"
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config user.email "surveyjs.org@gmail.com"
      git config user.name "surveyjsdeveloper"

      git fetch origin $branch
      git checkout -B $branch origin/$branch

      git add packages/survey-creator-core/src/localization
      git add packages/survey-creator-core/src/ui-preset-editor/localization
      if (git status --porcelain) {
          echo "There are changes in translations. Committing and pushing to GitHub..."
          git diff --cached --stat
          git commit -m "updated survey-creator translation for $branch [azurepipelines skip]"
          git push origin $branch
      }
      else {
          echo "No changes in translations. Skipping commit and push."
      }
    displayName: "l10n for $(Build.SourceBranchName)"
    env:
      TRANSLATION_API_KEY: $(TRANSLATION_API_KEY)

  - script: |
      npm run release -- --skip.tag
      npm run build:all
    workingDirectory: $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    displayName: "Build"

  - pwsh: |
      Set-Location $(Build.SourcesDirectory)/surveyjs-site-data
      $branch = "$(siteDataRef)"
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config user.email "surveyjs.org@gmail.com"
      git config user.name "surveyjsdeveloper"

      git fetch origin $branch
      git checkout -B $branch origin/$branch
      git reset --hard origin/$branch

      Set-Location $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npx survey-utils generate-doc creator-site --path $(Build.SourcesDirectory)/survey-creator --out $(Build.SourcesDirectory)/surveyjs-site-data/DocsEditor

      Set-Location $(Build.SourcesDirectory)/surveyjs-site-data
      git add DocsEditor
      if (git status --porcelain) {
          echo "There are changes in docs. Committing and pushing to GitHub..."
          git diff --cached --stat
          git commit -m "updated survey-creator docs for $branch [azurepipelines skip]"
          git push origin $branch
      }
      else {
          echo "No changes in docs. Skipping commit and push."
      }
    displayName: "Docs for $(Build.SourceBranchName)"
