jobs:
  - job:
    steps:
      - checkout: self
        persistCredentials: true
        displayName: "Checkout survey-creator"
        timeoutInMinutes: 5

      - checkout: Utils
        displayName: "Checkout survey-utils"
        timeoutInMinutes: 5

      - checkout: SiteData
        persistCredentials: true
        displayName: "Checkout survey-site-data"
        timeoutInMinutes: 5

      - template: ../utils/artifact.yml
        parameters:
          artifacts:
            - $(ArtifactNameLibraryCore)

      - pwsh: |
          $dest = "$(Build.SourcesDirectory)/survey-library/packages/survey-core/build"
          New-Item -ItemType Directory -Force -Path $dest | Out-Null
          Copy-Item -Recurse -Force "$(Agent.TempDirectory)/$(ArtifactNameLibraryCore)/*" $dest
        displayName: "Provide survey-core build"

      - template: ../utils/npm.yml
        parameters:
          directories:
            - $(Build.SourcesDirectory)/survey-creator
            - $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core

      - pwsh: |
          Set-Location $(Build.SourcesDirectory)/survey-utils
          npm install
          npm run build
          node ./dist/translateCreator.js
          node ./dist/translateCreatorPresets.js

          Set-Location $(Build.SourcesDirectory)/survey-creator
          $branch = "$(Build.SourceBranchName)"
          $env:GIT_REDIRECT_STDERR = '2>&1'
          git config user.email "surveyjs.org@gmail.com"
          git config user.name "surveyjsdeveloper"

          git fetch origin $branch
          git checkout -B $branch origin/$branch

          git add packages/survey-creator-core/src/localization
          git add packages/survey-creator-core/src/ui-preset-editor/localization
          if (git status --porcelain) {
              echo "There are changes in translations. Committing and pushing to GitHub..."
              git diff --cached --stat
              git commit -m "updated survey-creator translation for $branch [azurepipelines skip]"
              git push origin $branch
          }
          else {
              echo "No changes in translations. Skipping commit and push."
          }
        displayName: "l10n for $(Build.SourceBranchName)"

      - script: |
          npm run release -- --skip.tag
          npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
        displayName: "Build"

      - pwsh: |
          Set-Location $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
          New-Item -ItemType Directory -Force -Path docs | Out-Null
          npm run doc_gen
          Copy-Item -Force "docs/surveyjs_definition.json" "build/surveyjs_definition.json"

          Set-Location $(Build.SourcesDirectory)/surveyjs-site-data
          $branch = "$(Build.SourceBranchName)"
          $env:GIT_REDIRECT_STDERR = '2>&1'
          git config user.email "surveyjs.org@gmail.com"
          git config user.name "surveyjsdeveloper"

          git fetch origin $branch
          git checkout -B $branch origin/$branch
          git reset --hard origin/$branch

          Copy-Item -Force "$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/docs/classes.json" "DocsEditor/"
          Copy-Item -Force "$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/docs/pmes.json" "DocsEditor/"
          Copy-Item -Force "$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/docs/surveyjs_definition.json" "DocsEditor/"

          git add DocsEditor
          if (git status --porcelain) {
              echo "There are changes in docs. Committing and pushing to GitHub..."
              git diff --cached --stat
              git commit -m "updated survey-creator docs for $branch [azurepipelines skip]"
              git push origin $branch
          }
          else {
              echo "No changes in docs. Skipping commit and push."
          }
        displayName: "Docs for $(Build.SourceBranchName)"
