parameters:
  - name: checkout
    type: string
    default: self
  - name: libraryCheckout
    type: string
    default: Library
  - name: store
    type: boolean
    default: false

steps:
  - checkout: ${{ parameters.checkout }}
    path: s
    displayName: "Checkout ${{ parameters.checkout }}"
    timeoutInMinutes: 5
    retryCountOnTaskFailure: 5
    fetchDepth: 1

  - script: git fetch origin pull/$(PR)/head && git checkout FETCH_HEAD
    workingDirectory: $(Build.SourcesDirectory)
    condition: ne(variables['PR'], '')
    displayName: "Switch to PR $(PR)"

  - checkout: ${{ parameters.libraryCheckout }}
    path: survey-library
    displayName: "Checkout survey-library"
    timeoutInMinutes: 5
    retryCountOnTaskFailure: 5
    fetchDepth: 1

  - script: git fetch origin pull/$(LIBRARY_PR)/head && git checkout FETCH_HEAD
    workingDirectory: $(Agent.BuildDirectory)/survey-library
    condition: ne(variables['LIBRARY_PR'], '')
    displayName: "Switch library to PR $(LIBRARY_PR)"

  - template: ../utils/npm.yml
    parameters:
      directories:
        - $(Agent.BuildDirectory)/survey-library
        - $(Agent.BuildDirectory)/survey-library/packages/survey-core
        - $(Build.SourcesDirectory)

  - script: npm run build:all
    workingDirectory: $(Agent.BuildDirectory)/survey-library/packages/survey-core
    displayName: "Build survey-core"

  - template: ../utils/copy.yml
    parameters:
      items:
        - source: $(Agent.BuildDirectory)/survey-library/packages/survey-core/build
          destination: $(Build.SourcesDirectory)/node_modules/survey-core

  - script: npm run build:all
    workingDirectory: $(Build.SourcesDirectory)
    displayName: "Build"

  - ${{ if eq(parameters.store, true) }}:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build/'
        ArtifactName: $(ArtifactNamePDF)
        publishLocation: 'Container'
        StoreAsTar: true
