jobs:
  - job:
    steps:
      - checkout: self
        displayName: "Checkout survey-pdf"
        timeoutInMinutes: 5

      - checkout: SiteData
        persistCredentials: true
        displayName: "Checkout survey-site-data"
        timeoutInMinutes: 5

      - template: ../utils/npm.yml
        parameters:
          directories:
            - $(Build.SourcesDirectory)/survey-pdf

      - template: ../utils/artifact.yml
        parameters:
          artifacts:
            - $(ArtifactNameLibraryCore)

      - template: ../utils/copy.yml
        parameters:
          items:
            - source: $(Agent.TempDirectory)/$(ArtifactNameLibraryCore)
              destination: $(Build.SourcesDirectory)/survey-pdf/node_modules/survey-core

      - script: |
          npm run release -- --skip.tag
          npm run build:all
        workingDirectory: $(Build.SourcesDirectory)/survey-pdf
        displayName: "Build"

      - pwsh: |
          Set-Location $(Build.SourcesDirectory)/survey-pdf
          npm run doc_gen
          Copy-Item -Force "docs/surveyjs_definition.json" "build/surveyjs_definition.json"

          Set-Location $(Build.SourcesDirectory)/surveyjs-site-data
          $branch = "$(Build.SourceBranchName)"
          $env:GIT_REDIRECT_STDERR = '2>&1'
          git config user.email "surveyjs.org@gmail.com"
          git config user.name "surveyjsdeveloper"

          git fetch origin $branch
          git checkout -B $branch origin/$branch
          git reset --hard origin/$branch

          Copy-Item -Force "$(Build.SourcesDirectory)/survey-pdf/docs/classes.json" "DocsPdf/"
          Copy-Item -Force "$(Build.SourcesDirectory)/survey-pdf/docs/pmes.json" "DocsPdf/"
          Copy-Item -Force "$(Build.SourcesDirectory)/survey-pdf/docs/surveyjs_definition.json" "DocsPdf/"

          git add DocsPdf
          if (git status --porcelain) {
              echo "There are changes in docs. Committing and pushing to GitHub..."
              git diff --cached --stat
              git commit -m "updated survey-pdf docs for $branch [azurepipelines skip]"
              git push origin $branch
          }
          else {
              echo "No changes in docs. Skipping commit and push."
          }
        displayName: "Docs for $(Build.SourceBranchName)"
