resources:
  pipelines:
    - pipeline: LibraryMain
      source: Library Main
      trigger: none

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  CurrentBranch: $(Build.SourceBranchName)
  ProjectId: '__PROJECT_ID__'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Dev'
  testConfiguration: 'Release'

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'NPM install'
  inputs:
    command: install
    verbose: false
    workingDir: $(Build.SourcesDirectory)/surveyjs.io

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- download: LibraryMain
  artifact: SurveyJSLibraryBuildCore

- download: LibraryMain
  artifact: SurveyJSLibraryBuildReact

- download: LibraryMain
  artifact: SurveyJSLibraryBuildAngular

- download: LibraryMain
  artifact: SurveyJSLibraryBuildVue3

- download: LibraryMain
  artifact: SurveyJSLibraryBuildSurveyUI

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '55'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSCreatorV2BuildCore'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '55'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSCreatorV2BuildReact'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '55'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSCreatorV2BuildAngular'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '55'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSCreatorV2BuildVue'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '55'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSCreatorV2BuildJS'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '42'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSWidgetsBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '37'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSAnalyticsBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '38'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyjsPDFbuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds'
    Contents: '**'
    RemoveDotFiles: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/LibraryMain/SurveyJSLibraryBuildCore/packages'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/LibraryMain/SurveyJSLibraryBuildReact/packages'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/LibraryMain/SurveyJSLibraryBuildAngular/packages'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/LibraryMain/SurveyJSLibraryBuildVue3/packages'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)/LibraryMain/SurveyJSLibraryBuildSurveyUI/packages'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSCreatorV2BuildCore'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/survey-creator-core'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSCreatorV2BuildReact'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/survey-creator-react'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSCreatorV2BuildAngular'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/survey-creator-angular'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSCreatorV2BuildVue'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/survey-creator-vue'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSCreatorV2BuildJS'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/survey-creator-js'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSWidgetsBuild/packages/survey-widgets'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/surveyjs-widgets'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSAnalyticsBuild/packages/survey-analytics'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/survey-analytics'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyjsPDFbuild/packages/survey-pdf'
    Contents: '**'
    TargetFolder: '$(Build.Repository.LocalPath)/surveyjs.io/DevBuilds/survey-pdf'
    OverWrite: true

- task: PowerShell@2
  displayName: 'Copy Specific Config'
  inputs:
    targetType: inline
    script: Copy-Item -Path '$(Build.Repository.LocalPath)/surveyjs.io/robots.tst' -Destination '$(Build.Repository.LocalPath)/surveyjs.io/robots.txt'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=$(Build.ArtifactStagingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(testConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: SurveyJSSite

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'SJS2'
    appType: 'webApp'
    WebAppName: 'surveyjstest'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/surveyjs.io.zip'