name: Deploy css-bridge-demos

trigger: none
pr: none

resources:
  webhooks:
    - webhook: sjsDemosPush
      connection: sjs-demos-incoming-webhook
      filters:
        - path: repository.name
          value: css-bridge-demos
        - path: ref
          value: refs/heads/main
          
jobs:
  - job: Deploy
    timeoutInMinutes: 70
    steps:
      - checkout: none
      - task: SSH@0
        displayName: make up-css-bridge-demos
        timeoutInMinutes: 60
        inputs:
          failOnStdErr: false
          sshEndpoint: 'sjsdemo'
          runOptions: commands
          commands: make -C /survey/env up-css-bridge-demos
