name: Deploy helpdesk demo

trigger: none
pr: none

resources:
  webhooks:
    - webhook: sjsDemosPush
      connection: sjs-demos-incoming-webhook
      filters:
        - path: repository.name
          value: supabase-helpdesk
        - path: ref
          value: refs/heads/main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    timeoutInMinutes: 70
    steps:
      - checkout: none
      - task: SSH@0
        displayName: make up-helpdesk
        timeoutInMinutes: 60
        inputs:
          failOnStdErr: false
          sshEndpoint: 'sjsdemo'
          runOptions: commands
          commands: make -C /survey/env up-helpdesk
